name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push model_service image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/model-service:latest ./model_service
        docker push ${{ secrets.DOCKER_USERNAME }}/model-service:latest

    - name: Build and push model_training image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/model-training:latest ./model_training
        docker push ${{ secrets.DOCKER_USERNAME }}/model-training:latest

    - name: Build and push model_updator image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/model-updator:latest ./model_updator
        docker push ${{ secrets.DOCKER_USERNAME }}/model-updator:latest

    - name: Build and push GUI image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/gui:latest ./gui
        docker push ${{ secrets.DOCKER_USERNAME }}/gui:latest

    - name: Set up kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deploy/deploy-all.yaml
